import { DatabaseSync } from 'node:sqlite';
import { existsSync, readdirSync, readFileSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Creates a fresh SQLite database for the test run and applies the canonical
 * migrations.
 *
 * Prisma's `migrate`/`db push` CLIs drive a Rust schema-engine subprocess over
 * piped stdio, which is unavailable in some sandboxes, so the SQL generated by
 * `prisma migrate diff` is applied here with Node's built-in `node:sqlite`.
 */
export function createTestDatabase(name: string): string {
  const here = dirname(fileURLToPath(import.meta.url));
  const serverRoot = join(here, '..', '..');
  const databaseFile = join(serverRoot, 'prisma', `${name}.db`);

  for (const candidate of [
    databaseFile,
    `${databaseFile}-journal`,
    `${databaseFile}-wal`,
    `${databaseFile}-shm`,
  ]) {
    if (existsSync(candidate)) rmSync(candidate, { force: true });
  }

  let db: DatabaseSync;
  try {
    db = new DatabaseSync(databaseFile);
  } catch (error) {
    throw new Error(
      `Could not open the test database at ${databaseFile}: ${String(error)}\n` +
        `serverRoot=${serverRoot} exists=${existsSync(serverRoot)} ` +
        `prismaDir=${join(serverRoot, 'prisma')} exists=${existsSync(join(serverRoot, 'prisma'))}`,
    );
  }

  const migrationsDir = join(serverRoot, 'prisma', 'migrations');
  const folders = readdirSync(migrationsDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();

  for (const folder of folders) {
    const sqlFile = join(migrationsDir, folder, 'migration.sql');
    if (!existsSync(sqlFile)) continue;
    db.exec(readFileSync(sqlFile, 'utf8').replace(/^\uFEFF/, ''));
  }
  db.close();
  return databaseFile;
}

/** Absolute path of a test database (without creating it). */
export function testDatabasePath(name: string): string {
  const here = dirname(fileURLToPath(import.meta.url));
  return join(here, '..', '..', 'prisma', `${name}.db`);
}
