#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Orbit — deploy to the Hetzner VPS (Docker + Traefik stack on javistudio.dev).
#
# Run from a machine that can SSH to the `hetzner` host (see ~/.ssh/config):
#
#   bash scripts/deploy-hetzner.sh
#
# What it does, idempotently:
#   1. pushes the current branch to GitHub (the server pulls from there)
#   2. on the server: checkout/update /opt/orbit
#   3. writes /opt/orbit/.env (secrets, generated once, then reused)
#   4. builds the API image and the static client bundle on the server
#   5. `docker compose up -d` and waits for the health check
#   6. verifies the public HTTPS endpoint and the login API
#
# Options (environment variables):
#   SSH_HOST       default `hetzner`
#   DOMAIN         default `orbit.javistudio.dev`
#   APP_DIR        default `/opt/orbit`
#   BRANCH         default `master`
#   SEED           `true` (default on first deploy) loads the demo workspace
#   SKIP_PUSH      `true` to deploy the server's current checkout without pushing
# ---------------------------------------------------------------------------
set -Eeuo pipefail

SSH_HOST="${SSH_HOST:-hetzner}"
DOMAIN="${DOMAIN:-orbit.javistudio.dev}"
APP_DIR="${APP_DIR:-/opt/orbit}"
BRANCH="${BRANCH:-master}"
SKIP_PUSH="${SKIP_PUSH:-false}"
REPO_URL="${REPO_URL:-https://github.com/JaviPaez7/orbit.git}"

log() { printf '\n\033[1;36m▶ %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m⚠ %s\033[0m\n' "$*"; }
die() { printf '\033[1;31m✖ %s\033[0m\n' "$*" >&2; exit 1; }

remote() { ssh -o BatchMode=yes "$SSH_HOST" "$@"; }

# ---------------------------------------------------------------------------
# 1. Push so the server pulls exactly what was tested locally
# ---------------------------------------------------------------------------
if [[ "$SKIP_PUSH" != "true" ]]; then
  log "Pushing ${BRANCH} to GitHub"
  git push origin "$BRANCH"
fi

log "Checking SSH access to ${SSH_HOST}"
remote 'echo ok' >/dev/null || die "Cannot SSH to ${SSH_HOST}"

# ---------------------------------------------------------------------------
# 2. Secrets — generated once on the server and reused on every deploy
# ---------------------------------------------------------------------------
log "Preparing ${APP_DIR} and secrets"
remote "APP_DIR='${APP_DIR}' REPO_URL='${REPO_URL}' BRANCH='${BRANCH}' DOMAIN='${DOMAIN}' bash -s" <<'REMOTE_SETUP'
set -Eeuo pipefail
mkdir -p "$APP_DIR"
cd "$APP_DIR"

if [[ -d .git ]]; then
  git fetch --all --prune
  git checkout "$BRANCH"
  git reset --hard "origin/$BRANCH"
else
  git clone --branch "$BRANCH" "$REPO_URL" "$APP_DIR"
fi

SECRETS="$APP_DIR/.env"
if [[ ! -f "$SECRETS" ]]; then
  echo "generating new secrets"
  {
    echo "# Generated by scripts/deploy-hetzner.sh — never commit this file."
    echo "ORBIT_DOMAIN=$DOMAIN"
    echo "POSTGRES_USER=orbit"
    echo "POSTGRES_DB=orbit"
    echo "POSTGRES_PASSWORD=$(openssl rand -hex 24)"
    echo "AUTH_SECRET=$(openssl rand -hex 48)"
    echo "SEED_DEMO_DATA=true"
  } > "$SECRETS"
  chmod 600 "$SECRETS"
else
  echo "reusing existing secrets"
  # Keep the domain and seeding flag in sync with the current deploy.
  sed -i "s|^ORBIT_DOMAIN=.*|ORBIT_DOMAIN=$DOMAIN|" "$SECRETS"
fi
grep -q '^SEED_DEMO_DATA=' "$SECRETS" || echo "SEED_DEMO_DATA=true" >> "$SECRETS"
REMOTE_SETUP

# ---------------------------------------------------------------------------
# 3. Build the client bundle on the server (same-origin: no API host baked in)
# ---------------------------------------------------------------------------
log "Building the static client on the server"
remote "APP_DIR='${APP_DIR}' bash -s" <<'REMOTE_WEB'
set -Eeuo pipefail
cd "$APP_DIR"
export PATH="$PATH:/usr/local/bin"
# pnpm is already installed on this host (see the other apps on it).
pnpm install --frozen-lockfile
rm -rf apps/web/dist
VITE_API_URL="" VITE_WS_URL="" pnpm --filter @orbit/web build
rm -rf deploy/web-dist
cp -r apps/web/dist deploy/web-dist
echo "web bundle: $(du -sh deploy/web-dist | cut -f1)"
REMOTE_WEB

# ---------------------------------------------------------------------------
# 4. Build and start the stack
# ---------------------------------------------------------------------------
log "Building the API image and starting the stack"
remote "APP_DIR='${APP_DIR}' bash -s" <<'REMOTE_UP'
set -Eeuo pipefail
cd "$APP_DIR"
COMPOSE_PROJECT_NAME=orbit docker compose \
  --env-file "$APP_DIR/.env" \
  -f deploy/docker-compose.prod.yml up -d --build

echo "waiting for the API health check"
for attempt in $(seq 1 60); do
  status="$(docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' orbit-api 2>/dev/null || echo missing)"
  if [[ "$status" == "healthy" ]]; then
    echo "orbit-api is healthy"
    break
  fi
  if [[ "$attempt" == "60" ]]; then
    echo "--- orbit-api logs ---"
    docker logs --tail 80 orbit-api || true
    echo "health status: $status"
    exit 1
  fi
  sleep 3
done
REMOTE_UP

# ---------------------------------------------------------------------------
# 5. Verify from the outside
# ---------------------------------------------------------------------------
log "Verifying https://${DOMAIN}"
for attempt in $(seq 1 20); do
  if curl -fsS "https://${DOMAIN}/health" >/dev/null 2>&1; then
    log "TLS + routing OK: $(curl -fsS "https://${DOMAIN}/health")"
    break
  fi
  if [[ "$attempt" == "20" ]]; then
    warn "Public health check failed. Traefik may still be issuing the certificate."
    warn "Check with: ssh ${SSH_HOST} 'docker logs --tail 50 forge-traefik'"
  fi
  sleep 6
done

log "Verifying the login endpoint"
login_status="$(curl -s -o /dev/null -w '%{http_code}' -X POST "https://${DOMAIN}/api/auth/login" \
  -H 'Content-Type: application/json' \
  -d '{"email":"javi@orbit.dev","password":"Orbit1234"}' || echo 000)"
case "$login_status" in
  200) log "Login API OK (200) — demo data is seeded" ;;
  401) warn "Login returned 401: the API is up but the demo data is not seeded." ;;
  000) warn "Login request failed to connect" ;;
  *)   warn "Login returned HTTP ${login_status}" ;;
esac

cat <<EOF

────────────────────────────────────────────────────────────────
 Orbit deployed
────────────────────────────────────────────────────────────────
  App           https://${DOMAIN}
  Health        https://${DOMAIN}/health
  Demo login    javi@orbit.dev / Orbit1234

  On the server:
    cd ${APP_DIR}
    docker compose --env-file .env -f deploy/docker-compose.prod.yml ps
    docker logs -f orbit-api
    docker logs --tail 50 forge-traefik     # routing + certificates

  Redeploy:  bash scripts/deploy-hetzner.sh
────────────────────────────────────────────────────────────────
EOF
