#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Orbit — deploy to the Hetzner VPS (Docker + Traefik stack on javistudio.dev).
#
# Run from a machine that can SSH to the `hetzner` host (see ~/.ssh/config):
#
#   bash scripts/deploy-hetzner.sh
#
# Or run it directly *on* the VPS (no SSH hop):
#
#   LOCAL_MODE=true SKIP_PUSH=true bash /opt/orbit-src/scripts/deploy-hetzner.sh
#
# What it does, idempotently:
#   1. pushes the current branch to GitHub (the server pulls from there)
#   2. on the server: checkout/update /opt/orbit, generate secrets once, reuse later
#   3. builds the static client bundle
#   4. builds the API image, starts the stack, waits for the health check
#   5. verifies the public HTTPS endpoint and the login API
#
# Options (environment variables):
#   SSH_HOST       default `hetzner`
#   DOMAIN         default `orbit.javistudio.dev`
#   APP_DIR        default `/opt/orbit`
#   BRANCH         default `master`
#   SKIP_PUSH      `true` to deploy without pushing
#   LOCAL_MODE     `true` when running on the VPS itself
# ---------------------------------------------------------------------------
set -Eeuo pipefail

SSH_HOST="${SSH_HOST:-hetzner}"
DOMAIN="${DOMAIN:-orbit.javistudio.dev}"
APP_DIR="${APP_DIR:-/opt/orbit}"
BRANCH="${BRANCH:-master}"
SKIP_PUSH="${SKIP_PUSH:-false}"
LOCAL_MODE="${LOCAL_MODE:-false}"
REPO_URL="${REPO_URL:-https://github.com/JaviPaez7/orbit.git}"

log() { printf '\n\033[1;36m▶ %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m⚠ %s\033[0m\n' "$*"; }
die() { printf '\033[1;31m✖ %s\033[0m\n' "$*" >&2; exit 1; }

# Runs a script either locally or over SSH. The script is passed as an argument
# (base64-encoded so quoting can never break) rather than on stdin, which keeps
# `bash -s` and local execution identical.
run_script() {
  local script="$1"
  local encoded
  encoded="$(printf '%s' "$script" | base64 | tr -d '\n')"
  if [[ "$LOCAL_MODE" == "true" ]]; then
    printf '%s' "$encoded" | base64 -d | bash
  else
    ssh -o BatchMode=yes "$SSH_HOST" "printf '%s' '$encoded' | base64 -d | bash"
  fi
}

log "Deploying Orbit to ${DOMAIN} (app dir ${APP_DIR}, branch ${BRANCH})"

# ---------------------------------------------------------------------------
# 1. Push so the server pulls exactly what was tested locally
# ---------------------------------------------------------------------------
if [[ "$SKIP_PUSH" != "true" && "$LOCAL_MODE" != "true" ]]; then
  log "Pushing ${BRANCH} to GitHub"
  git push origin "$BRANCH"
fi

if [[ "$LOCAL_MODE" != "true" ]]; then
  log "Checking SSH access to ${SSH_HOST}"
  if ! ssh -o BatchMode=yes -o ConnectTimeout=15 "$SSH_HOST" 'echo ok' >/dev/null; then
    die "Cannot SSH to ${SSH_HOST}"
  fi
fi

# ---------------------------------------------------------------------------
# 2. Checkout + secrets (generated once, then reused)
# ---------------------------------------------------------------------------
log "Preparing ${APP_DIR} and secrets"
run_script "$(cat <<REMOTE_SETUP
set -Eeuo pipefail
APP_DIR='${APP_DIR}'
REPO_URL='${REPO_URL}'
BRANCH='${BRANCH}'
DOMAIN='${DOMAIN}'

mkdir -p "\$APP_DIR"
cd "\$APP_DIR"

if [[ -d .git ]]; then
  git fetch --all --prune
  git checkout "\$BRANCH"
  git reset --hard "origin/\$BRANCH"
else
  git clone --branch "\$BRANCH" "\$REPO_URL" "\$APP_DIR"
fi

SECRETS="\$APP_DIR/.env"
if [[ ! -f "\$SECRETS" ]]; then
  echo "generating new secrets (first deploy)"
  {
    echo "# Generated by scripts/deploy-hetzner.sh - never commit this file."
    echo "ORBIT_DOMAIN=\$DOMAIN"
    echo "POSTGRES_USER=orbit"
    echo "POSTGRES_DB=orbit"
    echo "POSTGRES_PASSWORD=\$(openssl rand -hex 24)"
    echo "AUTH_SECRET=\$(openssl rand -hex 48)"
    echo "SEED_DEMO_DATA=true"
  } > "\$SECRETS"
  chmod 600 "\$SECRETS"
else
  echo "reusing existing secrets"
  sed -i "s|^ORBIT_DOMAIN=.*|ORBIT_DOMAIN=\$DOMAIN|" "\$SECRETS"
  grep -q '^SEED_DEMO_DATA=' "\$SECRETS" || echo "SEED_DEMO_DATA=true" >> "\$SECRETS"
fi

echo "checkout: \$(git -C "\$APP_DIR" rev-parse --short HEAD)"
REMOTE_SETUP
)"

# ---------------------------------------------------------------------------
# 3. Build the static client (same-origin: no API host is baked in)
# ---------------------------------------------------------------------------
log "Building the static client"
run_script "$(cat <<REMOTE_WEB
set -Eeuo pipefail
APP_DIR='${APP_DIR}'
cd "\$APP_DIR"
export PATH="\$PATH:/usr/local/bin:/root/.local/share/pnpm"

pnpm install --frozen-lockfile
rm -rf apps/web/dist
VITE_API_URL="" VITE_WS_URL="" pnpm --filter @orbit/web build
rm -rf deploy/web-dist
cp -r apps/web/dist deploy/web-dist
echo "web bundle: \$(du -sh deploy/web-dist | cut -f1)"
REMOTE_WEB
)"

# ---------------------------------------------------------------------------
# 4. Build the API image and start the stack
# ---------------------------------------------------------------------------
log "Building the API image and starting the stack (this takes a few minutes)"
run_script "$(cat <<REMOTE_UP
set -Eeuo pipefail
APP_DIR='${APP_DIR}'
cd "\$APP_DIR"

COMPOSE_PROJECT_NAME=orbit docker compose \
  --env-file "\$APP_DIR/.env" \
  -f deploy/docker-compose.prod.yml up -d --build

echo "waiting for the API health check"
for attempt in \$(seq 1 80); do
  status="\$(docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' orbit-api 2>/dev/null || echo missing)"
  if [[ "\$status" == "healthy" ]]; then
    echo "orbit-api is healthy"
    exit 0
  fi
  if [[ "\$attempt" == "80" ]]; then
    echo "--- orbit-api logs (tail) ---"
    docker logs --tail 60 orbit-api || true
    echo "health status: \$status"
    exit 1
  fi
  sleep 3
done
REMOTE_UP
)"

# ---------------------------------------------------------------------------
# 5. Verify from the outside
# ---------------------------------------------------------------------------
log "Verifying https://${DOMAIN}"
verified="false"
for attempt in $(seq 1 25); do
  if curl -fsS "https://${DOMAIN}/health" >/dev/null 2>&1; then
    log "TLS + routing OK: $(curl -fsS "https://${DOMAIN}/health")"
    verified="true"
    break
  fi
  sleep 6
done
if [[ "$verified" != "true" ]]; then
  warn "Public health check failed — Traefik may still be issuing the certificate."
  warn "Inspect with: ssh ${SSH_HOST} 'docker logs --tail 60 forge-traefik'"
fi

log "Verifying the login endpoint"
login_status="$(curl -s -o /dev/null -w '%{http_code}' -X POST "https://${DOMAIN}/api/auth/login" \
  -H 'Content-Type: application/json' \
  -d '{"email":"javi@orbit.dev","password":"Orbit1234"}' || echo 000)"
case "$login_status" in
  200) log "Login API OK (200) — demo data is seeded" ;;
  401) warn "Login returned 401: the API is up but the demo data is not seeded." ;;
  000) warn "Login request could not connect" ;;
  *) warn "Login returned HTTP ${login_status}" ;;
esac

cat <<EOF

────────────────────────────────────────────────────────────────
 Orbit deployed
────────────────────────────────────────────────────────────────
  App           https://${DOMAIN}
  Health        https://${DOMAIN}/health
  Demo login    javi@orbit.dev / Orbit1234

  On the server:
    cd ${APP_DIR}
    docker compose --env-file .env -f deploy/docker-compose.prod.yml ps
    docker logs -f orbit-api
    docker logs --tail 60 forge-traefik     # routing + certificates

  Redeploy:  bash scripts/deploy-hetzner.sh
────────────────────────────────────────────────────────────────
EOF
